### ISSUE TITLE
about class BilinearFeedForward(nn.Module) role in the model？

### ISSUE THREAD

**Issue by xiaobaitu123344** [LifeBeyondExpectations/ECCV22-PointMixer#14]
Hello author, I would like to ask you about the role of this module, I have collected a lot of information, read the principle of it, but do not understand its role in your model is what?

**Comment by LifeBeyondExpectations** [comment]
As stated in https://github.com/LifeBeyondExpectations/ECCV22-PointMixer/issues/14#issue-1465898006
Bilinear function is the one way of feature-wise aggregation using MLPs. 
However, instead of using MLPs, I directly call the function, torch.nn.Bilinear(...) for simplicity.

**Comment by xiaobaitu123344** [comment]
Thank you for your detailed explanation.

**Comment by LifeBeyondExpectations** [comment]
if you have any question, please reopen the issue.
