### ISSUE TITLE
About the environment - pointops2

### ISSUE THREAD

**Issue by student2312** [LifeBeyondExpectations/ECCV22-PointMixer#16]
Professor, thank you for your work. While running your code recently, I found that I ran into a few issues when configuring the environment with conda:
In the way of conda, the .yml has a pip way to install some packages, and what is pointops2? pip can not find and install it.

**Comment by LifeBeyondExpectations** [comment]
I guess that I need to further remove the wrong environment setup. Sorry.

pointops2 is located at the [link](https://github.com/LifeBeyondExpectations/ECCV22-PointMixer/tree/main/sem_seg/lib).
As you can see the code, I manually install pointops2 by following the steps
```
cd sem_seg/lib/pointops2
python setup.py install

cd sem_seg/lib/pointops
python setup.py install
```

Let me know if you have any issue.

**Comment by student2312** [comment]
thanks ,Professor.I'try it

**Comment by student2312** [comment]
Professor ,I am sorry to upset you. I got another question in your project. When I run command sh run_s3dis_PointMixer.sh, I got the error that there is no folder ../Stanford3dDataset_v1.2_Aligned_Version/trainval_fullarea. The origin S3DIS data has no folder that named  trainval_fullarea, I guess its a processed date based on S3DIS, and I have not foud how to process it yet.
